name: Check Changelog Format

on:
  push:

jobs:
  checking-format:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
      TAG: ${{ github.ref_name }}
      CHANGELOGTXT: git+https://github.com/geopozo/changelogtxt-parser
    defaults:
      run:
        working-directory: ./src/py/
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
      - name: Check format
        run: |
          uv run --python 3.12 --with "$CHANGELOGTXT" changelogtxt check-format
